# Generated by Django 5.2 on 2025-04-05 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'specialization',
                'verbose_name_plural': 'specializations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='headline')),
                ('bio_extended', models.TextField(blank=True, verbose_name='extended biography')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('twitter_handle', models.CharField(blank=True, max_length=50, verbose_name='twitter handle')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='linkedin URL')),
                ('github_username', models.CharField(blank=True, max_length=50, verbose_name='github username')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('speaking_experience', models.TextField(blank=True, verbose_name='speaking experience')),
                ('languages', models.CharField(blank=True, max_length=200, verbose_name='languages')),
                ('presentation_topics', models.TextField(blank=True, verbose_name='presentation topics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('specializations', models.ManyToManyField(blank=True, related_name='speakers', to='speakers.specialization', verbose_name='specializations')),
            ],
            options={
                'verbose_name': 'speaker profile',
                'verbose_name_plural': 'speaker profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('event_name', models.CharField(max_length=200, verbose_name='event name')),
                ('date', models.DateField(verbose_name='date')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('video_url', models.URLField(blank=True, verbose_name='video URL')),
                ('slides_url', models.URLField(blank=True, verbose_name='slides URL')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='speakers.speakerprofile', verbose_name='speaker')),
            ],
            options={
                'verbose_name': 'presentation',
                'verbose_name_plural': 'presentations',
                'ordering': ['-date'],
            },
        ),
    ]
